import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { C } from "../context.js";
export function ReportExport({ data }) {
    const [open, setOpen] = useState(false);
    function handleOpen() {
        setOpen(true);
        setTimeout(() => window.print(), 200);
    }
    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const globalScore = data.globalScore ?? 0;
    const regime = data.regime ?? "UNKNOWN";
    const scores = data.scores ?? [];
    const signals = (data.signals ?? []).slice(0, 3);
    const indicators = (data.indicators ?? []).slice(0, 6);
    const macroEvents = (data.macroEvents ?? []).slice(0, 3);
    return (_jsxs(_Fragment, { children: [_jsxs("button", { onClick: handleOpen, "data-report": "generate-btn", style: {
                    display: "flex",
                    alignItems: "center",
                    gap: 6,
                    padding: "7px 16px",
                    borderRadius: 8,
                    border: `1px solid ${C.border}`,
                    background: "transparent",
                    color: C.textSecondary,
                    fontSize: 13,
                    cursor: "pointer",
                    transition: "all 0.15s",
                    whiteSpace: "nowrap",
                }, onMouseEnter: (e) => {
                    e.currentTarget.style.borderColor = C.blue + "66";
                    e.currentTarget.style.color = C.blue;
                }, onMouseLeave: (e) => {
                    e.currentTarget.style.borderColor = C.border;
                    e.currentTarget.style.color = C.textSecondary;
                }, children: [_jsx("span", { style: { fontSize: 14 }, children: "\uD83D\uDCC4" }), "Generate Report"] }), _jsx("div", { className: "report-print-only", style: { display: "none" }, children: _jsxs("div", { className: "report-page", children: [_jsxs("div", { className: "report-header", children: [_jsx("h1", { children: "MarketPulse Daily Report" }), _jsx("p", { className: "report-date", children: date })] }), _jsxs("div", { className: "report-section", children: [_jsxs("div", { className: "report-score-line", children: ["Global Crash Score: ", _jsx("strong", { children: globalScore.toFixed(1) }), " (", scoreLabel(globalScore), ")"] }), _jsxs("div", { className: "report-regime", children: ["Market Regime: ", _jsx("strong", { children: regime })] })] }), scores.length > 0 && (_jsxs("div", { className: "report-section", children: [_jsx("h2", { children: "Market Status" }), scores.map((s) => (_jsxs("div", { className: "report-row", children: [s.market.toUpperCase(), ": ", _jsx("strong", { children: Number(s.crashScore).toFixed(1) }), " (", scoreLabel(Number(s.crashScore)), ")"] }, s.market)))] })), signals.length > 0 && (_jsxs("div", { className: "report-section", children: [_jsx("h2", { children: "Top Signals" }), signals.map((sig, i) => (_jsxs("div", { className: "report-row", children: [sig.action?.toUpperCase(), " ", sig.instrument, sig.entry != null ? ` @ ${sig.entry}` : "", sig.target != null ? ` | Target: ${sig.target}` : "", sig.confidence != null ? ` | Confidence: ${sig.confidence}%` : ""] }, i)))] })), indicators.length > 0 && (_jsxs("div", { className: "report-section", children: [_jsx("h2", { children: "Key Indicators" }), indicators.map((ind) => (_jsxs("div", { className: "report-row", children: [ind.name, ": ", ind.latestValue?.value != null ? Number(ind.latestValue.value).toFixed(2) : "—", ind.latestValue?.normalizedValue != null && (_jsxs("span", { className: "report-normalized", children: [" (normalized: ", Number(ind.latestValue.normalizedValue).toFixed(0), ")"] }))] }, ind.slug)))] })), data.geopoliticalRisk != null && (_jsxs("div", { className: "report-section", children: [_jsx("h2", { children: "Geopolitical Risk" }), _jsxs("div", { className: "report-row", children: ["Score: ", _jsx("strong", { children: data.geopoliticalRisk }), " (", geoLabel(data.geopoliticalRisk), ")"] }), data.geopoliticalHeadline && (_jsxs("div", { className: "report-row", children: ["Top Risk: ", data.geopoliticalHeadline] }))] })), macroEvents.length > 0 && (_jsxs("div", { className: "report-section", children: [_jsx("h2", { children: "Upcoming Macro Events" }), macroEvents.map((ev, i) => (_jsxs("div", { className: "report-row", children: [new Date(ev.date).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" }), " \u2014 ", ev.name, ev.impact && _jsxs("span", { className: "report-impact", children: [" (", ev.impact, " impact)"] })] }, i)))] })), _jsxs("div", { className: "report-footer", children: ["Generated by MarketPulse \u00B7 ", date] })] }) }), _jsx("style", { children: `
        @media print {
          body > * { display: none !important; }
          .report-print-only { display: block !important; }
          .report-page {
            font-family: Georgia, serif;
            color: #000;
            background: #fff;
            padding: 48px;
            max-width: 700px;
            margin: 0 auto;
            font-size: 13px;
            line-height: 1.6;
          }
          .report-header { border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 20px; }
          .report-header h1 { font-size: 20px; margin: 0 0 4px; }
          .report-date { font-size: 12px; color: #555; margin: 0; }
          .report-section { margin-bottom: 20px; page-break-inside: avoid; }
          .report-section h2 { font-size: 14px; margin: 0 0 8px; border-bottom: 1px solid #ccc; padding-bottom: 4px; text-transform: uppercase; letter-spacing: 0.05em; }
          .report-score-line { font-size: 16px; margin-bottom: 4px; }
          .report-regime { font-size: 13px; color: #333; }
          .report-row { padding: 3px 0; border-bottom: 1px solid #eee; }
          .report-normalized { color: #555; }
          .report-impact { color: #333; }
          .report-footer { border-top: 1px solid #ccc; padding-top: 12px; font-size: 11px; color: #888; text-align: center; margin-top: 32px; }
        }
      ` })] }));
}
function scoreLabel(score) {
    if (score < 25) return "Low";
    if (score < 50) return "Moderate";
    if (score < 60) return "High";
    if (score < 75) return "Warning";
    if (score < 90) return "Critical";
    return "Extreme";
}
function geoLabel(score) {
    if (score < 30) return "Low";
    if (score < 60) return "Moderate";
    if (score < 80) return "High";
    return "Critical";
}
